

<font face="verdana">
<center>

<table border=0 width=100%>
<tr bgcolor=#c0c0c0><td><center>&nbsp;
<h3><font face=verdana>Game Results</font></h3>
&nbsp;</center></td></tr>
</table>

<b>Wolverines Game Results<br>(Through games of Jul 06, 2022)</b>
                                        
<b>All games</b><p>

<table border=0>
<tr bgcolor="#00008b">
<td align=left  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>&nbsp;&nbsp;</b></td>
<td align=left  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>Date&nbsp;</b></td>
<td align=left  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>&nbsp;&nbsp;</b></td>
<td align=left  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>Opponent&nbsp;</b></td>
<td align=center  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>&nbsp;&nbsp;</b></td>
<td align=center  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>Score&nbsp;</b></td>
<td align=center  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>Overall&nbsp;<br>Record&nbsp;</b></td>
<td align=center  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>Conference<br>Record&nbsp;</b></td>
<td align=right  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>Time&nbsp;</b></td>
<td align=right  bgcolor="#00008b"><font face=verdana size=2 color="#ffffff"><b>&nbsp;<br>Attend&nbsp;</b></td>
</tr>
<tr bgcolor="#ffffff">
<td align=right><font face=verdana size=2 color="#000000">*&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">MAR 27, 2022&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">BENGALS BRESCIA          &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">L &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000"><a href="20220115.htm">14-42</a>&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">0-1-0&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">0-1-0&nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">2:35    &nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">    30&nbsp;</td>
</tr>
<tr bgcolor="#ffffff">
<td align=right><font face=verdana size=2 color="#000000">*&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">Apr 23, 2022&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">HONEY BADGERS FORMIG     &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">W&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000"><a href="20220136.htm">41-0</a>&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">1-1-0&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">1-1-0&nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">02:07   &nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">    20&nbsp;</td>
</tr>
<tr bgcolor="#ffffff">
<td align=right><font face=verdana size=2 color="#000000">*&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">May 08, 2022&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">at&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">Braves Bologna           &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">W&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000"><a href="20220152.htm">29-18</a>&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">2-1-0&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">2-1-0&nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">02:30   &nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">    40&nbsp;</td>
</tr>
<tr bgcolor="#ffffff">
<td align=right><font face=verdana size=2 color="#000000">*&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">May 21, 2022&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">at&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">Bengals Brescia          &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">L &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000"><a href="20220169.htm">6-42</a>&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">2-2-0&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">2-2-0&nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">02:35   &nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">   120&nbsp;</td>
</tr>
<tr bgcolor="#ffffff">
<td align=right><font face=verdana size=2 color="#000000">*&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">Jun 05, 2022&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">at&nbsp;</td>
<td align=left><font face=verdana size=2 color="#000000">Pretoriani Roma          &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">L &nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000"><a href="20220497.htm">7-10</a>&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">2-3-0&nbsp;</td>
<td align=center><font face=verdana size=2 color="#000000">2-3-0&nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">2.39    &nbsp;</td>
<td align=right><font face=verdana size=2 color="#000000">    30&nbsp;</td>
</tr>
</table>

<p>
<table border=0>
<tr bgcolor="#ffffff">
<td align=left><font face=verdana size=2 color="#000000">* indicates conference game&nbsp;</td>
</tr>
</table>

</center>
</font>


